<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Metaheuristic algorithm implementations for Metaheuristics.NET.</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" />
    <ProjectReference Include="..\Metaheuristics.Core\Metaheuristics.Core.csproj" />
  </ItemGroup>
</Project>
